name: Build and deploy dotnet core project to Azure Function App - fileingest-blobupload

on:
  push:
    branches:
      - master
    paths:
      - 'fileingest-blob-upload/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'fileingest-blob-upload'
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        shell: bash
        run: |
          cd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_90E9374E5EB04968B5DC5F7D36DB621F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_45908A996EF84175B70D5722BEB3EE67 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_183B321D49CB406891FA7F970454E670 }}

      - name: Deploy Function
        uses: Azure/functions-action@v1
        with:
          app-name: 'fileingest-blobupload'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
