name: Deploy Functions (fileingest-blob-upload)

on:
  push:
    branches: [ master ]
    paths:
      - 'fileingest-blob-upload/**'
  workflow_dispatch:

env:
  PROJECT_DIR: fileingest-blob-upload
  DOTNET_VERSION: '9.x'
  FUNC_APP: fileingest-weu

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish Functions
        working-directory: ${{ env.PROJECT_DIR }}
        run: dotnet publish -c Release -o ./publish

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4D35A320BB2B4FBC9792DFA256FE50C3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F7B193AB70A34AC7829E2D1C934C2577 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EB3D2875F9E14C67895F5D21F4D50599 }}

      - name: Deploy to Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNC_APP }}
          slot-name: Production
          package: ${{ env.PROJECT_DIR }}/publish

