name: Build and deploy dotnet core project to Azure Function App - fileingest-blob-upload

on:
  push:
    branches:
      - master
    paths:
      - 'fileingest-blob-upload/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'fileingest-blob-upload'
  DOTNET_VERSION: '9.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish Function
        run: |
          dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/*.csproj \
            -c Release \
            -o ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8694CB05AF6F4EAA9830141FF573B4E1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A8F3669FE6104FB8AFECE9D4B577808A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8AC44798ED7442908696C08DA72E4AAD }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: fileingest-blob-upload
          slot-name: Production
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output
